# SPDX-FileCopyrightText: Copyright (c) 2017-2026 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
AllCops:
  Exclude:
    - 'bin/**/*'
    - 'assets/**/*'
    - 'vendor/**/*'
  DisplayCopNames: true
  TargetRubyVersion: 3.3
  NewCops: enable
  SuggestExtensions: false
plugins:
  - rubocop-rake
  - rubocop-minitest
  - rubocop-performance
Layout/CaseIndentation:
  Enabled: false
Metrics/CyclomaticComplexity:
  Max: 10
Lint/RescueException:
  Enabled: false
Metrics/MethodLength:
  Max: 100
Metrics/ClassLength:
  Max: 250
Metrics/AbcSize:
  Max: 60
Metrics/BlockLength:
  Max: 50
Minitest/EmptyLineBeforeAssertionMethods:
  Enabled: false
Layout/MultilineMethodCallIndentation:
  Enabled: false
Layout/ElseAlignment:
  Enabled: false
Layout/EndAlignment:
  Enabled: false
Layout/IndentationWidth:
  Enabled: false
Metrics/PerceivedComplexity:
  Max: 10
Layout/EmptyLineAfterGuardClause:
  Enabled: false
