# SPDX-FileCopyrightText: Copyright (c) 2017-2025 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
docker:
  image: yegor256/rultor-image:1.21.0
readers:
  - "urn:github:526301"
assets:
  config.yml: yegor256/home#assets/sixnines/config.yml
  id_rsa: yegor256/home#assets/heroku-key
  id_rsa.pub: yegor256/home#assets/heroku-key.pub
install: |-
  sudo gem install openssl -- --with-openssl-dir=/usr/local/rvm/rubies/ruby-3.0.1/lib/ruby/3.0.0/openssl
  sudo apt-get update -y
  sudo apt-get install --yes libmagickwand-dev imagemagick
  pdd -f /dev/null
  sudo bundle install --no-color "--gemfile=$(pwd)/Gemfile"
release:
  sensitive:
    - config.yml
  script: |-
    bundle exec rake
    git remote add dokku dokku@dokku.sixnines.io:sixnines
    rm -rf ~/.ssh
    mkdir ~/.ssh
    mv ../id_rsa ../id_rsa.pub ~/.ssh
    chmod -R 600 ~/.ssh/*
    echo -e "Host *\n  StrictHostKeyChecking no\n  UserKnownHostsFile=/dev/null" > ~/.ssh/config
    git add .gitignore
    git fetch
    sed -i "s/BUILD/${tag}/g" ./version.rb
    git add ./version.rb
    git commit -m 'build number set'
    cp ../config.yml config.yml
    git add config.yml
    git commit -m 'config.yml'
    git push -f dokku $(git symbolic-ref --short HEAD):master
    git reset HEAD~1
    rm -rf config.yml
    curl -f --connect-timeout 15 --retry 5 --retry-delay 30 http://www.sixnines.io > /dev/null
merge:
  script: |-
    bundle exec rake
